// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwy6kdcoBnepy0uHqyp567ioqm4X7OQtE',
    appId: '1:570012497364:web:ecc9d7b8f238e191491241',
    messagingSenderId: '570012497364',
    projectId: 'flash-chat-887f0',
    authDomain: 'flash-chat-887f0.firebaseapp.com',
    storageBucket: 'flash-chat-887f0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClSp-iwU0zBZspxFPg2cJB8yrqcuH-E-I',
    appId: '1:570012497364:android:541b78fb1846b978491241',
    messagingSenderId: '570012497364',
    projectId: 'flash-chat-887f0',
    storageBucket: 'flash-chat-887f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi0G02cb7WuixSZNyptIrYwJMr8Q_h7-0',
    appId: '1:570012497364:ios:c538e30a588a0634491241',
    messagingSenderId: '570012497364',
    projectId: 'flash-chat-887f0',
    storageBucket: 'flash-chat-887f0.appspot.com',
    iosClientId: '570012497364-knb3p491c4v797p51bt2pd39826mo58u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );
}
